language: java
branches:
    only:
      - master
matrix:
    fast_finish: true
    include:
      - arch: arm64
        jdk: openjdk11
        os: linux
        name: "Linux Java LTS"
      - arch: amd64
        jdk: openjdk11
        os: linux
        name: "Linux Java LTS"
        
